apiVersion: v1
kind: Secret
metadata:
  name: dlna-hub-secret
  namespace: dlna-hub
type: Opaque
stringData:
  TMDB_API_KEY: "04b705dd3c3b8f2d4a8555066aaeeaa0"
  TMDB_API_READ_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNGI3MDVkZDNjM2I4ZjJkNGE4NTU1MDY2YWFlZWFhMCIsIm5iZiI6MTc4NjIyODEzMS4zNjcsInN1YiI6IjZhNzdhZGEzYzBjMmRmNDc0N2RlNWRiZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.8u9ruhVCfThLsrNqb1crJB2vhZ9SBorW1tfLNIwTVDw"
